version: '3.1'

services:
  web:
    image: odoo
    
    depends_on:
      - db
    
    ports:
      - "8069:8069"
    
    restart: always
    
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    
    command: -u all -d rd-demo
    
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

    
  db:
    image: postgres

    ports:
      - "5432:5432"
    
    restart: always

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata

    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    
    #command: psql rd-demo
    
volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass